pipeline {
    agent any
    parameters {
        booleanParam defaultValue: false, name: 'blPackerShell'
        booleanParam defaultValue: false, name: 'blPackerAnsible'
        booleanParam defaultValue: false, name: 'blApplyAWS'
        booleanParam defaultValue: false, name: 'blTestAnsible'
        booleanParam defaultValue: false, name: 'blUpdateAWS'
        booleanParam defaultValue: false, name: 'blDestroy'

    }
    options {
        ansiColor('xterm')
    }
/*    environment {
        AZ_CRED = credentials('Azure_William')
    } */
    stages {
        stage('Packer Shell') {
            when {expression{return params.blPackerShell}}
            steps {
                withAWS(credentials: 'AWS_JR8', region: 'ap-southeast-2') {
                    // some block
                    dir('packer/1.bake-ec2-to-image-shell-provisioner') {
                        sh '''
                            packer init .
                            packer fmt .
                            packer validate .
                            packer build aws-shell.pkr.hcl
                        '''
                    }
                }
            }
        }
        stage('Packer Ansible') {
            when {expression{return params.blPackerAnsible}}
            steps {
                withAWS(credentials: 'AWS_JR8', region: 'ap-southeast-2') {
                    // some block
                    dir('packer/2.bake-ec2-to-image-ansible-provisioner') {
                        sh '''
                            packer init .
                            packer fmt .
                            packer validate .
                            packer build aws-ansible.pkr.hcl
                        '''
                    }
                }
            }
        }
        stage('Launch Instances') {
            when {expression{return params.blApplyAWS}}
            steps {
                withAWS(credentials: 'AWS_JR8', region: 'ap-southeast-2') {
                    // some block
                    dir('terraform/aws') {
                        sh '''
                            terraform init
                            terraform apply --auto-approve
                        '''
                    }
                }
            }
        }
        stage('Test Ansible') {
            when {expression{return params.blTestAnsible}}
            steps {
                withAWS(credentials: 'AWS_JR8', region: 'ap-southeast-2') {
                    // some block
                    dir('ansible') {
                        sh '''
                            ansible all  -m ping
                            ansible tag_shell -a "cat /home/ubuntu/hello.txt"
                            ansible tag_ansible -a "curl localhost"
                        '''
                    }
                }
            }
        }
        stage('Update AWS EC2') {
            when {expression{return params.blUpdateAWS}}
            steps {
                withAWS(credentials: 'AWS_JR8', region: 'ap-southeast-2') {
                    // some block
                    dir('ansible') {
                        sh '''
                            ansible-playbook jenkins_docker.yml 
                        '''
                    }
                }
            }
        }
        stage('Destroy Instances') {
            when {expression{return params.blDestroy}}
            steps {
                withAWS(credentials: 'AWS_JR8', region: 'ap-southeast-2') {
                    // some block
                    dir('terraform/aws') {
                        sh '''
                            terraform destroy --auto-approve
                        '''
                        sh 'chmod +x ./del_ami.sh && ./del_ami.sh'
                    }
                }
            }
        }
    }
}
